name: flutterrific_opentelemetry
description: "A Flutter package for OpenTelemetry based on dartastic_opentelemetry"
version: 0.3.0
homepage: https://dartastic.io
repository: https://github.com/MindfulSoftwareLLC/flutterrific_opentelemetry.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartastic_opentelemetry: ^0.8.1
  dartastic_opentelemetry_api: ^0.8.0
  #TODO - need to manage go_router dependency versions and no-go-router implementation
  go_router: ^15.1.2
  meta: ^1.16.0
  uuid: ^4.5.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
